import Head from 'next/head'
import { useState, useEffect, useContext } from 'react'
import axios from 'axios'
/* import Image from 'next/image' */
/* import { Inter } from 'next/font/google' */
import styles from '@/styles/Home.module.css'
import Carousel from '@/components/Carousel/Carousel'
import ListMovies from '@/components/ListMovies/ListMovies'
import { FavContext } from '@/context/FavoritesContext'





export default function Home({ movies, populars }) {
 
  const { fav, setFav } = useContext(FavContext)

  useEffect(()=>{
    localStorage.setItem("Favorites", JSON.stringify(fav))
  },[fav])

  const [inputValue, setInputValue] = useState('')
  const [ dataApi, setDataApi ] = useState([])


const handleChangeSearch = (e)=>{
  const SEARCH_API = 'https://api.themoviedb.org/3/search/movie?api_key=6bf591cad6e4cf5174a3c96637ab3530&language=es-ES'
    setInputValue(e.target.value)
    axios.get(`${SEARCH_API}&query=${inputValue}`)
      .then(res => res.data)
      .then( data => setDataApi(data.results) )
}


  return (
    <>
      <Head>
        <title>Movies Plus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Carousel pops={populars} />
        <div className='row mt-3 d-flex justify-content-center align-items-center gap-3'>
          <div className='d-flex justify-content-center align-items-center gap-3'>
          <input  onChange={handleChangeSearch} className='outline-0 p-1 w-25' type='text'  placeholder='Search'></input>
          </div>
        {
          inputValue === '' ?  <ListMovies data={movies} /> :  <ListMovies data={dataApi} /> 
        }
          
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const api = process.env.URL_API
  const res = await fetch(api)
  const movies = await res.json()

  const apiPopular = process.env.URL_API_POPULAR
  const response = await fetch(apiPopular)
  const populars = await response.json()

  return {
    props: {
      movies: movies.results,
      populars: populars.results
    }
  }
}